#!/bin/bash

: '
**Author** Fonyuy Boris Lami

**Occupation** Data Scientist and Software Developer

**School** Carnegie Mellon University

**Description of dirwc**
dirwc does a line count, word count and character count of files in a given directory passed as an argument with the
current directory as default if no argument is parsed and prints line count, word count and character count to the screen

**Usage**
dirwc [DIRPATH] 

**Last Modified**
13th of October 2021 at 12h14 [GMT + 2]
 '

# At most 2 args
if [[ "$#" -gt 1 ]] 
then
   	echo -e "...ending dirwc ... at most 1 args required\n\nUsage\n dirwc [DIRPATH]"
   	exit 1
else
	if [ "$#" -eq 0 ]
	then
	    echo -e "No directory. Using default current directory\n\nUsage\n dirwc [DIRPATH]"
	    DIRWC=./
	elif [[ "$#" -eq 1 ]] && [[ -d $1 ]]
	then
	    DIRWC=$1
	fi
fi


# Output results to screen
echo $DIRWC"  "`wc $(find $DIRWC -name '*.*' -type f) | tail -1 | rev | cut -d ' ' -f 2-5 | rev`

# finish
if [ "$?" -ne 0 ]
then
    echo -e "An error occured! contact author: Fonyuy Boris Lami (lami-genius on github)\n"
fi
